### ISSUE TITLE
Remove the space at the end of the line

### ISSUE THREAD

**Issue by huruka** [dongfg/vscode-beancount-formatter#11]
For various reasons, there are spaces at the end of some lines in my txn bean file.
It would be great if it can automatically remove these spaces after formatted.

**Comment by dongfg** [comment]
Have you try to set `files.trimTrailingWhitespace` in vscode?
When enabled, will trim trailing whitespace when saving a file.

**Comment by huruka** [comment]
oh great, it is very useful
thanks!
