### ISSUE TITLE
金额自动对齐时，无法将中文字符识别为2个字符。

### ISSUE THREAD

**Issue by ZinngRui** [dongfg/vscode-beancount-formatter#18]
Dong先生，您好！您的插件非常棒，感谢您的分享！

我在使用中发现，账户信息是纯英文时，对齐的很完美，但是中英文混合的账户，无法对齐。

<a href="url"><img src="https://i.loli.net/2021/06/24/Ff5G3jhKDESX1qu.png" align="center" height="70%"  width="70%"  ></a>

我使用的是严格的等宽字体，2个英文字母（不区分大小写）宽度 = 1个中文宽度。
经过我的测试，证实formatter插件没有将1个中文的宽度和1个英文字母的宽度进行区分，两者的宽度被视为是一样的。

以下这两行字符数是一样多，格式化后是这样：

<a href="url"><img src="https://i.loli.net/2021/06/24/YFtBfg6DC247RGr.png" align="center" height="70%"  width="70%"  ></a>

1个中文的宽度，实际占用了2个英文字母的空间。第一行一共有8个中文，我们在第二行补上8个英文字母后，金额就对齐了：

<a href="url"><img src="https://i.loli.net/2021/06/24/uJV78QWahDoGbiO.png" align="center" height="70%"  width="70%"  ></a>

[参考字体](https://github.com/be5invis/Sarasa-Gothic/releases)

参考代码：
` Expenses:食品烟酒:烟酒:酒类                                          500.00 CNY`
` Expenses:abcd:ab:ab                                          600.00 CNY`
` abcdababExpenses:abcd:ab:ab                                          600.00 CNY`

我的个人代码能力很差，希望您能在有空的时候，解决一下这个问题。
万分感谢！

**Comment by ZinngRui** [comment]
您好！vscode-beancount最近在0.7.0版本上解决了无法将中文字体识别为2个字符的[问题](https://github.com/Lencerf/vscode-beancount/pull/55)。希望他的代码对您有些帮助。谢谢！

**Comment by dongfg** [comment]
> 您好！vscode-beancount最近在0.7.0版本上解决了无法将中文字体识别为2个字符的[问题](https://github.com/Lencerf/vscode-beancount/pull/55)。希望他的代码对您有些帮助。谢谢！

我周末看下吧

**Comment by dongfg** [comment]
> 您好！vscode-beancount最近在0.7.0版本上解决了无法将中文字体识别为2个字符的[问题](https://github.com/Lencerf/vscode-beancount/pull/55)。希望他的代码对您有些帮助。谢谢！

发了个新版本`1.4.1`，参考你说的这个实现的，添加了一样的选项，fixedCJKWidth，默认 false。

**Comment by ZinngRui** [comment]
> > 您好！vscode-beancount最近在0.7.0版本上解决了无法将中文字体识别为2个字符的[问题](https://github.com/Lencerf/vscode-beancount/pull/55)。希望他的代码对您有些帮助。谢谢！
> 
> 发了个新版本`1.4.1`，参考你说的这个实现的，添加了一样的选项，fixedCJKWidth，默认 false。

感谢您！已更新使用，太棒了！给你点赞o(￣▽￣)ｄ

**Comment by whusnoopy** [comment]
不好意思，这个修复里有一个小 bug，对于带中文的行，`padEnd` 的宽度计算有误，如果中文行不是最宽的一行，对齐还是有问题

已经提交带测试的 https://github.com/dongfg/vscode-beancount-formatter/pull/19
