### ISSUE TITLE
Publish on Open VSX

### ISSUE THREAD

**Issue by Vinfall** [dongfg/vscode-beancount-formatter#20]
Hello!

Would you mind publishing your extension on [Open VSX registry](https://open-vsx.org/)? Packages such as [code](https://www.archlinux.org/packages/community/x86_64/code/) or [vscodium](https://github.com/VSCodium/vscodium) can't use Visual Studio Marketplace due to the fact that their [Terms of Use](https://aka.ms/vsmarketplace-ToU) restricts it only to Microsoft's products.

Here are the [publishing instructions](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). It comes down to adding ovsx publish command in addition to your normal `vsce publish`.

Thanks for making this extension!

Note: the text is copied from [vscode-beancount issue](https://github.com/Lencerf/vscode-beancount/issues/47).

**Comment by dongfg** [comment]
https://open-vsx.org/extension/dongfg/vscode-beancount-formatter

- [x] **Published**
